### ISSUE TITLE
stringify objects?

### ISSUE THREAD

**Issue by stephenmathieson** [Floby/node-sse-writer#1]
I'm using SSE to emit small chunks of JSON and am repetitively serializing objects on my own. Ideally, I'd just be able to do this:

```js
stream.event('something', { foo: 'bar' })
```

Would you be open to look at a PR that adds support for stringifying objects?

**Comment by Floby** [comment]
PR obviously welcome =)

**Comment by stephenmathieson** [comment]
Awesome, I'll play around with it soon

**Comment by Floby** [comment]
I ended up doing it :)
