### ISSUE TITLE
vim undo files in package

### ISSUE THREAD

**Issue by goto-bus-stop** [Floby/node-sse-writer#2]
Thanks for publishing this module! I was looking for something lightweight, but a bit nicer than manually concatenating strings, and this is just perfect :)

The latest release contains a bunch of vim undo files: https://unpkg.com/sse-writer@3.0.0/

Perhaps you'd like to do a patch release without those files?

**Comment by Floby** [comment]
Sorry about that, npm is supposed to use gitignore rules but only check local ignore list and not global ones. WIll fix

**Comment by Floby** [comment]
@goto-bus-stop Go my .npmignore file in order. Now you only got what you need =)
published in `3.0.2`

**Comment by goto-bus-stop** [comment]
thanks! :rocket:
